# Generated by Django 5.0.1 on 2024-02-03 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(default='image', upload_to='products/'),
        ),
    ]
